### ISSUE TITLE
Missing file in backend/config/

### ISSUE THREAD

**Issue by mdvsh** [cryptichunt/platform#4]
While setting the repo up locally, the command

```console
$ cp config/config.example.json config/config.json
``` 
executed in `./cryptocracy-platform/backend` gives the following error :

```console
cp: cannot stat 'config/config.example.json': No such file or directory
```

The example config file isn't available in the directory where it should be according to the README and is missing.

**Comment by dotangad** [comment]
Hey, thanks for the issue. This file is not required to run the platform, if you're free you can send us a PR which removes this line from the README.
